### ISSUE TITLE
test on any images

### ISSUE THREAD

**Issue by xwjBupt** [YvanYin/VNL_Monocular_Depth_Prediction#1]
Hi,thanks for sharing the code!

Right now,i want to use your code(test_any_images.py) to generate depth map for my own dataset,but the shape of the output of your model(use the pretrained kitti_official.pth ) is [1,100,300,400],can i get only one channel output like the right part of  while still using your pretrained model?

**Comment by YvanYin** [comment]
Hi,
the output channel of kitti model is 100. This output will be processed by function "bins_to_depth" to transfer depth bins to a one channel depth. 
You can test any images with test_any_images.py.

**Comment by xwjBupt** [comment]
hi,thanks for your reply , i tried to use the "bins_to_depth" function,but the pixels in result depth image are all zero,what should i do ? the following is the your code i changed a lit bit or i will show error:
```
            img_torch = scale_torch(img, 255)

            img_torch = img_torch[None, :, :, :].cuda()

            pred_depth, pred_depth_softmax = model.depth_model(img_torch)
            # pred_depth = pred_depth.cpu().numpy().squeeze()
            # pred_depth_scale = (pred_depth / pred_depth.max() * 60000).astype(np.uint16)
            
            
            pred_depth_scale = (pred_depth / pred_depth.max() * 60000)
            depth_map = own_bins_to_depth(pred_depth_scale)
            depth_map = depth_map.cpu().numpy()[0][0]
            plt.imshow(depth_map)
            plt.show()
           
```

**Comment by YvanYin** [comment]
Hi, can you send me your predicted results? or send me your tested images?

**Comment by xwjBupt** [comment]
hi！can i send your through email? what is your email address? thankd you!

**Comment by YvanYin** [comment]
My email is wei.yin@adelaide.edu.au.

**Comment by coldmanck** [comment]
So what's the right way to test on any images? This issue seems to be not solved yet.

**Comment by CVDOU** [comment]
Can you provide an example to show how to test? It seems using current codes cannot succeed testing.

**Comment by fire17** [comment]
Hey im also trying to run test_any_images
getting an error 
Traceback (most recent call last):
  File "test_any_images.py", line 82, in <module>
    cv2.imwrite((pathS + 'raw'+str(c)+'.png'), pred_depth_scale)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:667: error: (-215:Assertion failed) image.channels() == 1 || image.channels() == 3 || image.channels() == 4 in function 'imwrite_'

shape of pred_depth_scale is (150, 370, 370)

please help

**Comment by fire17** [comment]
> hi,thanks for your reply , i tried to use the "bins_to_depth" function,but the pixels in result depth image are all zero,what should i do ? the following is the your code i changed a lit bit or i will show error:
> 
> ```
>             img_torch = scale_torch(img, 255)
> 
>             img_torch = img_torch[None, :, :, :].cuda()
> 
>             pred_depth, pred_depth_softmax = model.depth_model(img_torch)
>             # pred_depth = pred_depth.cpu().numpy().squeeze()
>             # pred_depth_scale = (pred_depth / pred_depth.max() * 60000).astype(np.uint16)
>             
>             
>             pred_depth_scale = (pred_depth / pred_depth.max() * 60000)
>             depth_map = own_bins_to_depth(pred_depth_scale)
>             depth_map = depth_map.cpu().numpy()[0][0]
>             plt.imshow(depth_map)
>             plt.show()
>            
> ```

tried as xwjBupt suggested, saves us from error,
but also getting almost all 0 black image
and it takes wayyyyy longer with bins_to_depth

how do we get to vis/save pred_depth_scale properly??

**Comment by YvanYin** [comment]
Hi all,
I am so sorry for replying so late. I have modified the ./tools/test_any_images.py.  I provide some images for testing under ./test_any_images_examples. 

All the problems are that the output from model.depth_model(img_torch) should be processed by the bins_to_depth. This function will transfer the depth bins, which have 150 channels, to a 1 channel depth map.

**Comment by CVDOU** [comment]
> Hi all,
> I am so sorry for replying so late. I have modified the ./tools/test_any_images.py. I provide some images for testing under ./test_any_images_examples.
> 
> All the problems are that the output from model.depth_model(img_torch) should be processed by the bins_to_depth. This function will transfer the depth bins, which have 150 channels, to a 1 channel depth map.

Thanks for reply. I test as your suggestion, however, I still can't get the same results as provided. My results are shown below. The only difference is that I comment the code lines about dataset, as I don't have the  NYU dataset.

![26_r-raw](https://user-images.githubusercontent.com/54888228/65295888-69042480-db95-11e9-9f49-cb601c3353b7.png)
![107_r-raw](https://user-images.githubusercontent.com/54888228/65295894-6c97ab80-db95-11e9-9f93-13c8c6d849b9.png)

**Comment by YvanYin** [comment]
Do you use the script ./tools/test_any_images.py?
Can you check the following parts?
1) Have you successfully loaded the trained model?
2) check any pixel location of pred_depth_softmax, which is in the shape of [1, 150, w, h].  The sum of 150 channels should be 1. And you can also see that the probability of one channel is much bigger than the others.

**Comment by CVDOU** [comment]
> Do you use the script ./tools/test_any_images.py?
> Can you check the following parts?
> 
> 1. Have you successfully loaded the trained model?
> 2. check any pixel location of pred_depth_softmax, which is in the shape of [1, 150, w, h].  The sum of 150 channels should be 1. And you can also see that the probability of one channel is much bigger than the others.
> 
> I updated the code again. Please git the latest one.
> Run the following code to test any images.
> python ./tools/test_any_images.py
> --dataroot ./
> --dataset any
> --cfg_file lib/configs/resnext101_32x4d_nyudv2_class
> --load_ckpt ./nyu_rawdata.pth

Great. The reason is that the model isn't loaded. I can get the same results.

**Comment by kHarshit** [comment]
Hey @YvanYin, I'm getting 
```
Traceback (most recent call last):
  File "./tools/test_any_images.py", line 5, in <module>
    from lib.utils.net_tools import load_ckpt
ModuleNotFoundError: No module named 'lib'
```
even after adding the VNL lib directory to PATH like this:
`export PATH=/nfs/interns/kharshit/DepthEstimation/VNL_Monocular_Depth_Prediction/lib/:$PATH`

**Comment by Bill-Ren** [comment]
how can I test on a single image? I follow your steps, but it still has errors, it seems that the code can only test on dataset with labels?
