### ISSUE TITLE
Inpainting method used on dataset.

### ISSUE THREAD

**Issue by mengtan00** [YvanYin/VNL_Monocular_Depth_Prediction#10]
I notice that the vacuity in ground truth of NYU dataset has been filled. I'd like to know the method you use on inpainting dataset and whether it helps the performance of the network. Also, is the same method used to inpaint KITTI dataset? Thank you!

**Comment by YvanYin** [comment]
Hi, I used the inpainted depth for all the experiments, including the NYU and KITTI. Many previous methods also take the inpainted depth. I have never done a comparison of using the raw depth and inpainting depth.

**Comment by mengtan00** [comment]
Thanks for your response. Could you please give me more details about the inpainting method you use, like papers which describe this method?

**Comment by YvanYin** [comment]
Hi, sorry for replying late. I directly use the inpainting method provided by NYU dataset.
