### ISSUE TITLE
unit for tools/test_any_images.py prediction?

### ISSUE THREAD

**Issue by wangzheallen** [YvanYin/VNL_Monocular_Depth_Prediction#11]
It is good to know your wonderful work.
I use the provided image and script, and log the max/min value for the predicted depth before scaling 60000 https://github.com/YvanYin/VNL_Monocular_Depth_Prediction/blob/master/tools/test_any_images.py#L66.

For image 
107_r.png
max: 0.6463524
min: 0.110629596
For image 
26_r.png
max:0.5862275
min: 0.10630702
may I know the unit for these prediction? meters? or?

**Comment by IvanBarabanau** [comment]
@wangzheallen did you find out, how to retrieve the depth in meters?

**Comment by wangzheallen** [comment]
Kitti multiply by 80 and nyu multiply by 10
