### ISSUE TITLE
Convert network output to meters.

### ISSUE THREAD

**Issue by IvanBarabanau** [YvanYin/VNL_Monocular_Depth_Prediction#12]
Hi!
Could you please clarify, how is it possible to convert network depth output, bounded between 0 and 1, to real-world values in meters?

**Comment by YvanYin** [comment]
Hi,
when I train the model, I have normalized the depth to 0~1. On NYU, the max depth distance is 10m, so you multiply 10 to obtain the distance in meters. On KITTI，you multiply 80.

**Comment by IvanBarabanau** [comment]
@YvanYin 
Thank you for a quick reply!

How do you think, what a strategy of real-world depth retrieval should be, as the pretrained model on KITTI, for instance, is applied to a randomly selected image?

**Comment by YvanYin** [comment]
if you use the model trained on KITTI, you can still multiply 80 to get the metric depth. However, as the model has only been trained on KITTI, it cannot generalize to the diverse real-world environment.

**Comment by kunlileo** [comment]
Hi YvanYin ,

it is really terrific what you and your team achieved with the new model. My respect to you. 

I am currently working on a project, in which I could use precise Depth results generated, e.g by your work. But i am facing a problem with the output. As you addressed a above, when using the on kitti pretrained model to estimate the depth, we need to multiply the results with 80. But even if when I do so, the results are still not right. I used your KITTI pretrained model to predict the depth of the images from KITTI Object Detection. When I transform this depth into xyz coordinates, the pixel point cloud doesn't look right at all. As a comparision, when I use the PSMNet to estimate the Depth for those images, the results look acceptable. I was hoping you may know the reason of it and can help me out. I used the "test_any_image.py" script and adjusted the Path for '--dataroot', '--cfg_file' and '--load_ckpt' in "parse_arg_base". For your understanding, I attached the results generated by PSMNet (1st Image) and your Model (2nd Image).
![000000](https://user-images.githubusercontent.com/12843016/71212592-eaad4080-22b1-11ea-888c-90e056f87762.png)
(PSMNet)

![000000](https://user-images.githubusercontent.com/12843016/71212631-00bb0100-22b2-11ea-9feb-50c670b84d9a.png)
(VNL)

Thanks in advanced.
