### ISSUE TITLE
How to process NYU datest

### ISSUE THREAD

**Issue by haoxurt** [YvanYin/VNL_Monocular_Depth_Prediction#15]
Thanks for your share. I have a question on processing NYU datest, in your nyudv2_dataset.py,  the depth image divide 10, what type of depth image should  input?  what are the value range of depth image? 0-65535?  
Thanks

**Comment by YvanYin** [comment]
Hi,
I have normalized the depth value to 0~1 for training. 
If you use the officially split data, which is in the *.mat format, the largest range of depth is 10m. Therefore, I divide the depth by 10m. If you use the depth image and the depth range is 0-65535, you should divide 65535.

**Comment by haoxurt** [comment]
Thanks for your answer。 I have followed your readme and download NYU by Eigen splited,  I find the number of images is 1449, where I can find another 29K which you used in the train pahse?

**Comment by YvanYin** [comment]
We download the whole raw data of NYU and randomly selected 29K images. You can also download the raw data to select images.
