### ISSUE TITLE
The test metric on nyu v2 is not the same as the result in paper?

### ISSUE THREAD

**Issue by csuwoshikunge** [YvanYin/VNL_Monocular_Depth_Prediction#17]
Thanks for sharing. For nyu v2, I downloaded the data and trained model you provide. After running the test code, I got the following result:
rel = 0.10590, log10= 0.04602, **rms=0.48770**, delta1=0.88267, delta2= 0.97619, deltat3=0.99389.
But the metrics in your paper are:
rel= 0.108, log10=0.048, **rms=0.416**, delta1=0.875, delta2=0.976, delta3=0.994.
There seems to be large differences in the rms metric. Did I misunderstand some details? 
Thanks for any help.

**Comment by YvanYin** [comment]
There are many models, and I pick up one model and upload it.

**Comment by ITking666** [comment]
> 
> 
> Thanks for sharing. For nyu v2, I downloaded the data and trained model you provide. After running the test code, I got the following result:
> rel = 0.10590, log10= 0.04602, **rms=0.48770**, delta1=0.88267, delta2= 0.97619, deltat3=0.99389.
> But the metrics in your paper are:
> rel= 0.108, log10=0.048, **rms=0.416**, delta1=0.875, delta2=0.976, delta3=0.994.
> There seems to be large differences in the rms metric. Did I misunderstand some details?
> Thanks for any help.

hello,can you share your "test_annotations.json" file

**Comment by ITking666** [comment]
hello,can you share your "test_annotations.json" file
