### ISSUE TITLE
How do you calculate the GT VN?

### ISSUE THREAD

**Issue by LiZhenLiangLee** [YvanYin/VNL_Monocular_Depth_Prediction#19]
In your paper, you mention that predicted VN are calculated from the reconstructed point cloud. How about GT VN? How to get it?

**Comment by YvanYin** [comment]
Hi, the predicted and GT VN are obtained from the predicted Point cloud and GT Point cloud, respectively. The point cloud is reconstructed from the depth.

**Comment by LiZhenLiangLee** [comment]
thanks for quick reply!
