### ISSUE TITLE
Calculation of Sq_Rel Error

### ISSUE THREAD

**Issue by wyfeng1020** [YvanYin/VNL_Monocular_Depth_Prediction#24]
Hi,
I think there is a small typo in the metrics code: https://github.com/YvanYin/VNL_Monocular_Depth_Prediction/blob/17ba0242371576c7168e4ed46df990168169796a/lib/utils/evaluate_depth_error.py#L224, where the equation of sq_rel should be (pred-gt)^2/gt rather than (pred-gt)^2/gt^2.

**Comment by yosungho** [comment]
I think it is (pred-gt)^2/gt^2, which is written in code.
