### ISSUE TITLE
val_annotations.json is missing.

### ISSUE THREAD

**Issue by aufaclav** [YvanYin/VNL_Monocular_Depth_Prediction#29]
1. Hi, thank you for sharing the code. I tried to run the training code and apparently, there is only train annotation and test annotation. val_annotations.json is missing. Can you share the file? or where i can find it.  or do i need to create by myself from available data? 

Which part of program that i need to change to skip the validation process and directly to test? 
where i can change the opt.phase?

Thank you

**Comment by YvanYin** [comment]
Hi, if you do not want to do the validation during training, just remove the validation code in the train.py:

>val_err[0] = val(val_dataloader, model)

Besides, you should change the 'parse_arg_val.py'. 
--anno_phase='train'

**Comment by aufaclav** [comment]
Thank you for your response. I finished the problem. thanks to you..

now i faced another problem with test.. i tried to test with pre-trained data
python  ./tools/test_any_images.py \
		--dataroot    ./ \
		--dataset     any \
		--cfg_file     lib/configs/resnext101_32x4d_nyudv2_class \
		--load_ckpt   model/nyu_rawdata.pth

i downloaded the pretrain data and give it into the created model folder. But the result is strange. When i open it, all images becomes grey and has 50000 value. i tried it with your images in example, and the result are the same. Is there something wrong with my procedure?

here is the example result
![107_r-raw](https://user-images.githubusercontent.com/44729224/80291971-93811600-8752-11ea-81cd-0b20ad037962.png)

**Comment by YvanYin** [comment]
Sorry for late reply. Have you fixed this problem?

**Comment by aufaclav** [comment]
Yes, i solved this problem.

However, i have another problem when i do the training. after initialization i get this error

RuntimeError: normal_ expects std > 0.0, but found std=0

I still struggling with this..

**Comment by aufaclav** [comment]
Which pytorch did you use?

**Comment by aufaclav** [comment]
Yes, i solved it already.

Can i ask another question? 
i have a dataset with the same structure of train.mat.
i want to update/fine tune the nyu_rawdata.pth with my dataset.
Can i just load and train it with resume option?

**Comment by YvanYin** [comment]
Hi, if out of memory, you can adjust the image size for training. Please see the config file under lib/core/config.py. You can adjust it to 256*256 or others.

Yes, you can. However, you should set the new learning rate for fine-tuning.
