### ISSUE TITLE
Only can train 1 epoch?

### ISSUE THREAD

**Issue by yyangmei** [YvanYin/VNL_Monocular_Depth_Prediction#33]
Hello, when I use your train code to train on nyu, I can only train 1 epoch.
When start to train the scend epoch, the process will stuck at `for i, data in enumerate(train_dataloader)`.
How can I solve this problem?Thank you so much.

**Comment by YvanYin** [comment]
Hi, can you remove all the training codes part, just load the data in a loop to check if it can work?
For example:
`for i, data in enumerate(train_dataloader):
    print(i)`

**Comment by yyangmei** [comment]
Thank you,I remove all training codes and it can work.
But it can't with training codes.
I want to train my own model, what can I do to solve it?

**Comment by YvanYin** [comment]
Hi, I have not faced this problem before. 
What is your PyTorch version and CUDA version? 
Where is the process stuck at?
Besides, our code will do the evaluation every 2000 iterations. Can you check if it is in the evaluation?

**Comment by YvanYin** [comment]
When you remove the network forward codes, is it can work?
Can for i, data in enumerate(train_dataloader)  successfully run to the second epoch and successfully load the data?

**Comment by yyangmei** [comment]
Yes, if I remove the forward codes it can work and load data successfully on the secend epoch.

**Comment by YvanYin** [comment]
Hi, I think the problem maybe is the GPU memory. You can set a smaller batch size and monitor the GPU memory. You can see that without the forward codes it can smoothly load all data.

**Comment by yyangmei** [comment]
Thank you so much!
I have solved the problem by reconfiguring the environment.

**Comment by tnaderi** [comment]
Hi, Thank you for sharing your code. I have the same problem. It seems that it is able to train the model but when it is done with first epoch or get into evaluation it stop working just stay idle! I do not know how to fix this problem. Could you please help me in this regard, thank you
