### ISSUE TITLE
how to get the surface normal image

### ISSUE THREAD

**Issue by ITking666** [YvanYin/VNL_Monocular_Depth_Prediction#34]
Dear YvanYin:
I missed a problem when  test your masterpiece,which is that i can't  get  surface normal image from depth image and RGB image ,would you  please tell me how to get it.

**Comment by YvanYin** [comment]
Hi, I will try to find the code for recovering the surface normal. 
You can read this:
https://stackoverflow.com/questions/34644101/calculate-surface-normals-from-depth-image-using-neighboring-pixels-cross-produc
It is very helpful for you to understand how to recover surface normal. However, you should recover (x, y, z) for each pixel before calculating its surface normal

**Comment by ITking666** [comment]
Thank you so much  for your kind reply.
But I still want to konw how did you  get the depth estimation results by Junjie Hu  (Revisiting Single Image Depth Estimation: Toward Higher Resolution Maps With Accurate Object Boundaries)  and convert these depth images to surface normal map .

**Comment by YvanYin** [comment]
Hi, can you send me an email, I can send you the code.

**Comment by ITking666** [comment]
Thank you very much and my mails is 1474690467@qq.com

**Comment by ITking666** [comment]
Thank you very much and my mails is 1474690467@qq.com

**Comment by LeisureLiu** [comment]
Hi, 
I have tried to understand  the link @YvanYin gives, but faild.  Could you please send me the code too. My email is 407055993@qq.com. Looking forward to your reply and thank you very much.

**Comment by kwea123** [comment]
@YvanYin Hi, the link you provide gives a good insight but is not directly applicable here as it doesn't take into account the camera parameters. As you suggested, the correct way should be to backproject each pixel into 3d xyz then calculate the normals. However I struggle to find an efficient and concise implementation... I'm also surprised that I cannot find any resource on google as it seems to be a common problem. Anyway, can you provide the code in this repo? Thank you.

**Comment by YvanYin** [comment]
Hi all, I will post my code for recovering the surface normal from the point cloud.

**Comment by YvanYin** [comment]
Please check /tools/recover_surface_normal.py.

**Comment by ITking666** [comment]
Thank you very much


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YvanYin/VNL_Monocular_Depth_Prediction"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 上午9:34
收件人:&nbsp;"YvanYin/VNL_Monocular_Depth_Prediction"<VNL_Monocular_Depth_Prediction@noreply.github.com&gt;;
抄送:&nbsp;"1474690467"<1474690467@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [YvanYin/VNL_Monocular_Depth_Prediction] how to get the surface normal image (#34)





 
Please check /tools/recover_surface_normal.py.
