### ISSUE TITLE
About the VNL_loss

### ISSUE THREAD

**Issue by LeisureLiu** [YvanYin/VNL_Monocular_Depth_Prediction#37]
Hi, Thank you for your amazing works.
There is an question confuse me. I found that you use  the center of the random croped image' s  as the u0 and v0 to reconstruct point clouds in VNL_loss. Won't it get wrong result?

**Comment by YvanYin** [comment]
Hi, during training, we directly use the cropped image center as the u0v0. As gt and predicted depth consistently use that center, I believe that there is no problem. You can think that gt and predicted depth take the same transformation.
