### ISSUE TITLE
Depth prediction and surface normal

### ISSUE THREAD

**Issue by aghasaadmohammad** [YvanYin/VNL_Monocular_Depth_Prediction#39]
While getting output as depth prediction, its in 3 channel(greyscale), but surface normal wants 4 channel image and i am having this error when i am feeding depth image to the surfacenormal file
![image](https://user-images.githubusercontent.com/61001884/89519856-77cbe800-d7f6-11ea-970b-bb6451d523fe.png)

**Comment by YvanYin** [comment]
The depth should be in 4 channels, i.e. Batchsize, channel, Height, Width.
