### ISSUE TITLE
 Data set format

### ISSUE THREAD

**Issue by Unitshockresponse** [YvanYin/VNL_Monocular_Depth_Prediction#41]
Hi,YvanYin:
Thanks for your great work! 
I want to use my own data set to train this model. The data set contains depth images and rgb images. How can I generate .mat files and .josn files?
How to convert image data into the format of your data set?
Thank you so much for your help!

**Comment by YvanYin** [comment]
Hi, 
If you just want to create your own .json file for training, you can follow https://github.com/YvanYin/VNL_Monocular_Depth_Prediction/blob/master/datasets/KITTI/README.md.
In the .json file, you only need to prepare the path for rgb data and depth data.
