### ISSUE TITLE
About point group size

### ISSUE THREAD

**Issue by LiZhenLiangLee** [YvanYin/VNL_Monocular_Depth_Prediction#42]
In your paper's  ablation studies, you discussed the impact of point group size.
The result shows that 80K is the best(though it's just slightly better than 20K).
But in your code, I find your point group size is 385* 385 * 0.15 = 22233,  about 22K.
Why don't you choose larger point group size?  consider the computation performance? You found that  22K is the best trade-off between model performance and computation ?

**Comment by YvanYin** [comment]
We didn't do more experiments to analyze the size of the sampled points. We just did some naive experiments to illustrating that more points can enhance the performance.
