### ISSUE TITLE
About NYUDv2 training dataset

### ISSUE THREAD

**Issue by youzunzhi** [YvanYin/VNL_Monocular_Depth_Prediction#46]
Hi! I wonder if you may share your dataset when training the SOTA NYUDv2 model, which you referred to as "20k unlabeled images" (but it has to be labeled since you need depth supervision during training, right?).

**Comment by andyhahaha** [comment]
The same question. 
In the paper, you said the model is trained with NYUD-large
The NYUD-large is 29K sampled image. But how do you get the depth groud truth?
NYUDv2 only provide 1449 densely labeled pairs, right?
And could you provide the NYUD-large for us to reproduce your results?
Thanks!

**Comment by YvanYin** [comment]
Hi, I cannot find the data on my cloud drive. If you want to reproduce the result, you can first use the whole training data first. If you have problems with training, we can discuss the issue later.
