### ISSUE TITLE
Pretrained Weights

### ISSUE THREAD

**Issue by kopetri** [YvanYin/VNL_Monocular_Depth_Prediction#47]
Deare YvanYin,

Great work!
I was wondering if you were using pretrained weights for resnext50, resnext101, and mobilnet from torchvision. 
Because I am not able to load torchvision weights with your code.

I would be happy if you could help me here.

Thank you!

**Comment by zhanghao00925** [comment]
You can find pre-train model here : https://github.com/YvanYin/VNL_Monocular_Depth_Prediction/issues?q=is%3Aissue+is%3Aclosed
