### ISSUE TITLE
When will you release the training code?

### ISSUE THREAD

**Issue by stulin** [YvanYin/VNL_Monocular_Depth_Prediction#5]
It is a wonderful work, and I want to train the network on my own dataset, when will you release the   training code? Or would you mind to send the code to me by email ?

**Comment by Tantoyy** [comment]
Me too.

**Comment by lypkuss** [comment]
Me too.

**Comment by wangjingbo1219** [comment]
Me too

**Comment by LiZhenLiangLee** [comment]
I really want  training code.

**Comment by doantientai** [comment]
Still looking forward your training code :D

**Comment by YvanYin** [comment]
The code is released.
