### ISSUE TITLE
Depth in meters 

### ISSUE THREAD

**Issue by utsavpatel22** [YvanYin/VNL_Monocular_Depth_Prediction#50]
Hello, Thank you so much for sharing this code. I am working on a project where we need to get the pedestrian velocities. To estimate the velocities, I need the depth information. We are using a depth camera for real-world implementation, but I need to run the same code on a dataset of monocular images to evaluate our algorithm. I am using your code to get the depth frames, but I am not sure about the unit of depth in the output depth frames. Is there a way to get the depth in meters?

**Comment by YvanYin** [comment]
Hi, which model do you use?

**Comment by utsavpatel22** [comment]
Hi @YvanYin, I am using ResNext101_32x4d backbone, trained on NYU dataset model. Will there be a difference in the estimated depth for different models?

**Comment by YvanYin** [comment]
Yes, there are some differences. When train the model on NYU, the farthest depth is 10m, while it is 80m on KITTI.

**Comment by guyueyanfeng** [comment]
Hi, @YvanYin , 
Is it true that the depth range in kitti is 80m? I find out that the pred_depth_scale multiply 60000 in the test_any_images. Is it possible that the depth range in kitti is 60m?
![图片](https://user-images.githubusercontent.com/30621422/223001707-e400f0cd-6c5a-4492-a892-41451400b299.png)
