### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Chen-che-w** [YvanYin/VNL_Monocular_Depth_Prediction#53]
Hello, I used nyu's pretrained model
But the value of rmse is 0.488
This seems to be much different from 0.416 in the paper
Want to know the reason and if there are any changed parameters?

**Comment by YvanYin** [comment]
Hi, previously I have trained several models, I randomly upload one.

**Comment by YvanYin** [comment]
Hi Chen,

I am sorry for the late reply. Your email is in my junk bins.

We have trained several different models and randomly upload one. We don't change the parameters. It seems that the released model has better performance on relative error. Therefore, we release that one.

Best,
Wei


________________________________
