### ISSUE TITLE
Error while loading the model

### ISSUE THREAD

**Issue by baegwangbin** [YvanYin/VNL_Monocular_Depth_Prediction#54]
Hi, 

When I try to run "./tools/test_nyu_metric.py", I get the following error.

...
    load_ckpt(test_args, model)
  File "./lib/utils/net_tools.py", line 42, in load_ckpt
    checkpoint = torch.load(args.load_ckpt)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 549, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 4136290587108604434 got 512

I think it may be because multiple processes were writing to the same checkpoint file (https://github.com/NVIDIA/apex/issues/515). I was wondering if you are getting the same error.

Thanks!

**Comment by YvanYin** [comment]
Hi,

I am sorry for late reply.
This email is in my junk bins.

Have you solved this problem?

Best,
Wei

________________________________
