### ISSUE TITLE
How make inference on single image?

### ISSUE THREAD

**Issue by paklau99988** [YvanYin/VNL_Monocular_Depth_Prediction#56]
is script have? 

Thanks you

**Comment by YvanYin** [comment]
Hi, you can see the inference part.

# Test depth predictions on any images, please replace the data dir in test_any_images.py
 python  ./tools/test_any_images.py \
		--dataroot    ./ \
		--dataset     any \
		--cfg_file     lib/configs/resnext101_32x4d_nyudv2_class \
		--load_ckpt   ./nyu_rawdata.pth

**Comment by paklau99988** [comment]
Yes, I know but get this:
Traceback (most recent call last):
  File "./tools/test_any_images.py", line 5, in <module>
    from lib.utils.net_tools import load_ckpt
ModuleNotFoundError: No module named 'lib'

**Comment by paklau99988** [comment]
The library "lib" is outside, why would test_any_images.py recognize it?
