### ISSUE TITLE
Only can train 1 epoch?

### ISSUE THREAD

**Issue by tnaderi** [YvanYin/VNL_Monocular_Depth_Prediction#57]
Hi YvanYin,
Thank you for sharing your code. I can not train the model. When it  goes over small NYUV2 one time it becomes idle. Does not do anything. How can I solve this?
Best,
Taher Naderi

**Comment by tnaderi** [comment]
It seems to me that it can initialize randomly, but it can not initialized from a pretrained model.

**Comment by tnaderi** [comment]
I do not get your reported results in ablation study. Could you please tell me what setting you are using?

**Comment by YvanYin** [comment]
Please check the path of your pretrained weight. 
When you train the model on small NYU, you can set the LR to 0.01.
