### ISSUE TITLE
Some questions about surface normal estimation and robutness test

### ISSUE THREAD

**Issue by mei123hao** [YvanYin/VNL_Monocular_Depth_Prediction#59]
Hi YvanYin:
Thanks your excellent work. After reading your paper I have some questions?
(1)I found that you have robustness test for virtual normal and surface normal in the paper. how do you calculate the mean difference error ? can you release your code about your rubustness test? Thanks a lot !!
(2)In the code recover_surface_normal.py, I found you add Identity Matrix:
`ATA = ATA + eps_identity`
is this for avoiding singular problem when perform LU decompose when running
`n_img, _ = torch.solve(AT1, ATA)` ?
 (3) Can i understand that the method you use to recover surface normal is based on the SVD decompose method?
My email is 809741329@qq.com, mayby we can communicate through email, :D !!!

**Comment by YvanYin** [comment]
Hi,
1) which table or figure do you refer to?
2) Yes, it amis to avoid the singular problem.
3) This is a least-square fitting method.

**Comment by mei123hao** [comment]
Thanks for your replying ! The figure that i refer to is figure 5 in the paper, which is shown like following:
![image](https://user-images.githubusercontent.com/36464299/111726277-92ddfa80-88a3-11eb-8d8c-1c1dced06501.png)

**Comment by YvanYin** [comment]
Hi,
The Mean Difference Error is:  Err = 1/n sum(arccos (n_{i} * n_{i}^{*}) )
