### ISSUE TITLE
Might it be a small false figure reference of the paper uploaded on Arxiv?

### ISSUE THREAD

**Issue by EryiXie** [YvanYin/VNL_Monocular_Depth_Prediction#61]
Hi, thanks for your amazing work. 

During reading the paper, I probably found a small figure reference mistake in the article (from Arxiv). As the screenshot below, I believe that the Fig.15c should be actually Fig.5b, if I understood it correctly.

![image](https://user-images.githubusercontent.com/29309899/112965655-c2192500-9149-11eb-8a96-3e5359940de8.png)

**Comment by YvanYin** [comment]
Thank you very much.
