### ISSUE TITLE
how can I train with NYUD-V2 dataset

### ISSUE THREAD

**Issue by wuzht** [YvanYin/VNL_Monocular_Depth_Prediction#62]
Hi, in NYUD-V2, there are only 1449 labeled RGB and depth images, how can you train with unlabeled images in the dataset? Could you please tell me more about the training details of this dataset? I am trying to reproduce your results. Looking forward to your reply, thanks.

**Comment by YvanYin** [comment]
Hi,
You can download all data of NYUDV2, and remove the testing scenes as the training data. NYUDV2 provides the paired RGB and depth for each scene.
