### ISSUE TITLE
About the Camera Parameters

### ISSUE THREAD

**Issue by JennyGao00** [YvanYin/VNL_Monocular_Depth_Prediction#63]
In the ./lib/core/config.py, you set the # Camera Parameters # as:
# Camera Parameters
__C.DATASET.FOCAL_X = 1.0
__C.DATASET.FOCAL_Y = 1.0

However, i find that  the # Camera Parameters # in toolbox_nyu_depth_v2/camera_params.m are different with yours.
% RGB Intrinsic Parameters
fx_rgb = 5.1885790117450188e+02;
fy_rgb = 5.1946961112127485e+02;
% Depth Intrinsic Parameters
fx_d = 5.8262448167737955e+02;
fy_d = 5.8269103270988637e+02;

So, why you set it as 1.0 instead of 519 ?
Looking forward to your reply.

**Comment by YvanYin** [comment]
Hi,
Please see lib/configs/resnext101_32x4d_nyudv2_class.yaml.

**Comment by JennyGao00** [comment]
I get it now !  Thanks !
