### ISSUE TITLE
How to generate a point cloud map？

### ISSUE THREAD

**Issue by 18983683746** [YvanYin/VNL_Monocular_Depth_Prediction#65]
Hello,

How do I use the predicted depth map to generate a point cloud map？It seems does not contain this operation in your code....

**Comment by YvanYin** [comment]
When you get the depth map, you can use the following codes to create the point cloud:
`x = (u-u0)*z /f
y = (v-v0)*z/f
z = d`

(u0, v0) is the image coordinate of the optical center. f is the focal length. d is the depth. Then save them in the `ply` format, see https://pypi.org/project/plyfile/  for details.
