### ISSUE TITLE
pretaind resnext101_32x4d.pth

### ISSUE THREAD

**Issue by XiangZhou1** [YvanYin/VNL_Monocular_Depth_Prediction#67]
Hi, I am interested in your work. But  I cannot load the resnext101_32x4d.pth you have provided using your code (convert_state_dict)

the following code is not suitable for your Pretrained ResNeXt model.

def convert_state_dict(src_dict):    
    """Return the correct mapping of tensor name and value

    Mapping from the names of torchvision model to our resnet conv_body and box_head.
    """
    #print_state_dict(src_dict)
    dst_dict = {}

    ###########
    model_state_dict = src_dict["model_state_dict"]
    #############
    #print_state_dict(model_state_dict)

    res_id = 1
    map1 = ['conv1.', 'bn1.', ' ', 'conv2.', 'bn2.']
    map2 = [[' ', 'conv3.', 'bn3.'], ['shortcut.conv.', 'shortcut.bn.']]
    for k, v in model_state_dict.items():
    #for k, v in model_state_dict.items():
        toks = k.split('.')
        if int(toks[0]) == 0:
            name = 'res%d.' % res_id + 'conv1.' + toks[-1]
        elif int(toks[0]) == 1:
            name = 'res%d.' % res_id + 'bn1.' + toks[-1]
        elif int(toks[0]) >=4 and int(toks[0]) <= 7:
            name_res = 'res%d.%d.' % (int(toks[0])-2, int(toks[1]))
            if len(toks) == 7:
                name = name_res + map1[int(toks[-2])] + toks[-1]
            elif len(toks) == 6:
                name = name_res + map2[int(toks[-3])][int(toks[-2])] + toks[-1]
        else:
            continue
        dst_dict[name] = v

    return dst_dict

**Comment by YvanYin** [comment]
I used an old resnext implementation. I have forgotten where I got it. You can download the ImageNet pre-trained weight from  here: https://cloudstor.aarnet.edu.au/plus/s/J87DYsTlOjD83LR
