### ISSUE TITLE
nyu depth v2 preprocess

### ISSUE THREAD

**Issue by iammarvelous** [YvanYin/VNL_Monocular_Depth_Prediction#7]
Hi, in the paper, you mentioned there are 464 different indoor scenes and 249 of them are used for training. Could you let me know where I can get the training list of scenes? Also, could you clarify how did you sample the images from the training set? What's the sampling rate or how many frames in each scene did you sample?

**Comment by YvanYin** [comment]
I download the raw data of NYUDV2, and remove the scenes that exist in the testing data. I randomly sample the data from each scene.
