### ISSUE TITLE
不清楚是哪里配置不对？

### ISSUE THREAD

**Issue by 18022443868** [YvanYin/VNL_Monocular_Depth_Prediction#8]
File "E:\vSLAM\VNL_Monocular_Depth_Prediction-master\data\nyudv2_dataset.py", line 154, in depth_to_bins
    bins = ((torch.log10(depth) - cfg.DATASET.DEPTH_MIN_LOG) / cfg.DATASET.DEPTH_BIN_INTERVAL).to(torch.int)
TypeError: div(): argument 'other' (position 1) must be Tensor, not NoneType

**Comment by YvanYin** [comment]
Have you successfully loaded the data, e.t. depth.

**Comment by 18022443868** [comment]
有测试运行时间？以及运行是在CPU？





| |
任云
|
|
邮箱：18022443868@163.com
|

签名由 网易邮箱大师 定制

在2019年10月24日 07:30，Wei Yin 写道：

Have you successfully loaded the data, e.t. depth.

**Comment by YvanYin** [comment]
Sorry, I have never tested it on CPU.

**Comment by 18022443868** [comment]
ok,very thank you




| |
任云
|
|
邮箱：18022443868@163.com
|

签名由 网易邮箱大师 定制

在2019年10月24日 07:38，Wei Yin 写道：

Sorry, I have never tested it on CPU.
